name: docker

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
    
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (pip version)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: aws-sam-cli-pip.dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # Never push on pull-request
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-pip:${{ env.DOCKER_METADATA_OUTPUT_VERSION }},ghcr.io/zpascal/aws-sam-cli-container-pip:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (ARM64 version)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: aws-sam-cli-src-arm64.dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # Never push on pull-request
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (X86-64 version)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: aws-sam-cli-src-x86-64.dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }} # Never push on pull-request
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}