name: docker

on:
  pull_request:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Extract the image name for the Pip case and init meta elements
        run: |
          echo "IMAGE_NAME_PIP=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
          echo "CURRENT_DATE=`echo $(date +'%Y-%m-%d')`" >>${GITHUB_ENV}
          echo "AWS_SAM_CLI_VERSION=`echo ${AWS_SAM_CLI_VERSION}`" >>${GITHUB_ENV}
        env:
          AWS_SAM_CLI_VERSION: 1.115.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (source version)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: aws-sam-cli-src.dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # Never push on pull-request
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "AWS_SAM_CLI_VERSION=v${{ env.AWS_SAM_CLI_VERSION }}"
            "CURRENT_DATE=${{ env.CURRENT_DATE }}"

      - name: Build and push Docker image (pip version)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: aws-sam-cli-pip.dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # Never push on pull-request
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PIP }}-pip:${{ env.DOCKER_METADATA_OUTPUT_VERSION }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PIP }}-pip:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "AWS_SAM_CLI_VERSION=${{ env.AWS_SAM_CLI_VERSION }}"
            "CURRENT_DATE=${{ env.CURRENT_DATE }}"